apiVersion: v1
kind: Namespace
metadata:
  name: api-servers
spec: {}
status: {}
---
apiVersion: v1
data:
  docker-registry-secret: IyFAVmVyeVN0cjBuZ1NlY3JldDEhIwo=
kind: Secret
metadata:
  name: db-secrets
  namespace: api-servers
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nodejs-deploy
  name: nodejs-deploy
  namespace: api-servers
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: nodejs-deploy
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nodejs-deploy
  name: nodejs-deploy
  namespace: api-servers
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-deploy
  strategy:
    rollingUpdate:
      maxUnavailable: 2
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nodejs-deploy
    spec:
      containers:
      - env:
        - name: SECRET_PASSWORD
          valueFrom:
            secretKeyRef:
              key: docker-registry-secret
              name: db-secrets
        image: nodejs-api:latest
        name: nodejs-api
        ports:
        - containerPort: 8000
        resources:
          limits:
            cpu: 400m
          requests:
            cpu: 200m
status: {}
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: nodejs-deploy
  namespace: api-servers
spec:
  maxReplicas: 10
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 80
        type: Utilization
    type: Resource
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nodejs-deploy
