apiVersion: autoscaling/v2beta2
#apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-nodejs-deploy
  namespace: api-servers
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nodejs-deploy
    #  targetCPUUtilizationPercentage: 80
  maxReplicas: 10
  minReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
