apiVersion: v1
kind: Service
metadata:
  labels:
    app: nodejs-deploy
  name: srvc1
  namespace: api-servers
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: nodejs-deploy
  type: LoadBalancer

